version: 0.0
os: linux
files:
#  - source: /scripts/vhosts.conf
#    destination: /etc/nginx/conf.d/
  - source: /
    destination: /opt/Bachmans/Bachmans
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 60
  AfterInstall:
    - location: scripts/after.sh
      timeout: 1200
