version: 0.0
os: linux
files:
  - source: /scripts/vhosts.conf
    destination: /etc/nginx/conf.d/
  - source: /
    destination: /opt/alfresco-community/tomcat/webapps/Bachmans
permissions:
  - object: /var/www/
    pattern: "*"
    owner: ec2-user
    group: nginx
    mode: 775
    type:
      - directory
  - object: /var/www/
    pattern: "*"
    owner: ec2-user
    group: nginx
    mode: 755
    type:
      - file      
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh   
      timeout: 300
      runas: ec2-user
